#!/bin/sh

# This project is licensed under the MIT License (see LICENSE).

set -eu

usage() {
    echo 'usage: zram-swap command

commands:
  setup         Setup single device
  setup-per-cpu Setup a device per CPU
  remove        Remove devices
  on            Turn on devices
  off           Turn off devices
  status        Show status of devices'
}

setup() {
    ncpu=$(nproc)
    nram=$(free -b | awk '/^Mem:/ {print $2}')

    if [ "$1" = "true" ]; then
        modprobe zram num_devices="$ncpu"
        size=$((nram / ncpu))
        for i in $(seq 0 $((ncpu - 1))); do
            name="zram$i"
            zramctl "$name" -a lz4 -t "$ncpu" -s "$size"
            mkswap -L "$name" /dev/"$name"
        done
    else
        modprobe zram num_devices=1
        zramctl "zram0" -a lz4 -s "$nram"
        mkswap -L "zram0" /dev/zram0
    fi
}

remove() {
    zramctl -r /dev/zram*
    rmmod zram
}

on() {
    for f in /dev/zram*; do
        swapon -p 32767 "$f"
    done
}

off() {
    for f in /dev/zram*; do
        swapoff "$f"
    done
}

status() {
    swapon | awk 'NR==1 || /^\/dev\/zram/'
    exit
}

[ $# -eq 0 ] && status

case "$1" in
    setup) setup false && on ;;
    setup-per-cpu) setup true && on ;;
    remove) off && remove ;;
    on) on ;;
    off) off ;;
    status) status ;;
    *) usage >&2; exit 2
esac
